# Generated by Django 4.2 on 2026-04-06 05:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('matchmaking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompatibilityParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text="Matches the key in the astrology API response e.g. 'sun_compatibility'", max_length=50, unique=True)),
                ('label', models.CharField(help_text="Human readable label e.g. 'Sun Compatibility'", max_length=100)),
                ('is_free', models.BooleanField(default=False, help_text='Free users can see this parameter')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order in the response')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive parameters are excluded from responses')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FeatureFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_free_credits', models.PositiveIntegerField(default=5, help_text='Free credits given to every new user on registration')),
                ('paid_credit_price_usd', models.DecimalField(decimal_places=2, default=1.0, help_text='Price in USD per paid credit', max_digits=6)),
                ('credits_per_purchase', models.PositiveIntegerField(default=10, help_text='How many paid credits the user gets per purchase')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Feature Flag',
            },
        ),
        migrations.CreateModel(
            name='UserPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('free_credits', models.PositiveIntegerField(default=0)),
                ('paid_credits', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plan', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_usd', models.DecimalField(decimal_places=2, max_digits=8)),
                ('credits_purchased', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('payment_reference', models.CharField(blank=True, help_text='Payment gateway transaction ID e.g. Stripe charge ID', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
