# Generated by Django 4.2 on 2026-04-15 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0002_compatibilityparameter_featureflag_userplan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compatibilityscore',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
