# Generated by Django 4.2 on 2026-04-15 09:55

from django.db import migrations, models
import matchmaking.models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0003_compatibilityscore_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=matchmaking.models.user_profile_picture_upload_to),
        ),
    ]
