# Generated by Django 4.2 on 2026-04-17 08:11

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('matchmaking', '0006_make_userprofile_fields_optional'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMatchPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('non_binary', 'Non-binary'), ('other', 'Other'), ('any', 'Any')], max_length=30)),
                ('preferred_age_min', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(120)])),
                ('preferred_age_max', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(120)])),
                ('preferred_city', models.CharField(blank=True, max_length=100)),
                ('preferred_distance_km', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20000)])),
                ('preferred_relationship_intent', models.CharField(blank=True, choices=[('marriage', 'Marriage'), ('long_term', 'Long-term relationship'), ('casual', 'Casual dating'), ('friendship', 'Friendship'), ('open_to_explore', 'Open to explore')], max_length=30)),
                ('preferred_religion_community', models.CharField(blank=True, max_length=100)),
                ('preferred_mother_tongue', models.CharField(blank=True, max_length=100)),
                ('preferred_education', models.CharField(blank=True, max_length=150)),
                ('preferred_profession', models.CharField(blank=True, max_length=150)),
                ('preferred_marital_status', models.CharField(blank=True, choices=[('never_married', 'Never married'), ('divorced', 'Divorced'), ('widowed', 'Widowed'), ('separated', 'Separated'), ('annulled', 'Annulled'), ('any', 'Any')], max_length=30)),
                ('modern_methods', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('karmic_glue', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('ancient_methods', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('deal_maker', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('sizzle', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='match_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='usermatchpreference',
            index=models.Index(fields=['user'], name='matchmaking_user_id_aa0b53_idx'),
        ),
        migrations.AddIndex(
            model_name='usermatchpreference',
            index=models.Index(fields=['preferred_gender'], name='matchmaking_preferr_a61fa5_idx'),
        ),
        migrations.AddIndex(
            model_name='usermatchpreference',
            index=models.Index(fields=['preferred_relationship_intent'], name='matchmaking_preferr_5d00b8_idx'),
        ),
        migrations.AddIndex(
            model_name='usermatchpreference',
            index=models.Index(fields=['preferred_city'], name='matchmaking_preferr_a70c58_idx'),
        ),
    ]
