# Generated by Django 4.2 on 2026-04-18 09:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0007_usermatchpreference_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompatibilityTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_type', models.CharField(choices=[('free', 'Free'), ('paid', 'Paid')], max_length=10)),
                ('is_paid', models.BooleanField(default=False)),
                ('overall_score', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('credits_remaining_after', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('api_response', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('compatibility_score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='matchmaking.compatibilityscore')),
                ('matched_private_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compatibility_transactions', to='matchmaking.privateperson')),
                ('matched_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compatibility_transaction_matches', to='matchmaking.userprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compatibility_transactions', to='matchmaking.userprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='compatibilitytransaction',
            index=models.Index(fields=['user'], name='matchmaking_user_id_810365_idx'),
        ),
        migrations.AddIndex(
            model_name='compatibilitytransaction',
            index=models.Index(fields=['compatibility_score'], name='matchmaking_compati_94a77f_idx'),
        ),
        migrations.AddIndex(
            model_name='compatibilitytransaction',
            index=models.Index(fields=['created_at'], name='matchmaking_created_2f4c1f_idx'),
        ),
        migrations.AddConstraint(
            model_name='compatibilitytransaction',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('matched_private_person__isnull', True), ('matched_user__isnull', False)), models.Q(('matched_private_person__isnull', False), ('matched_user__isnull', True)), _connector='OR'), name='one_transaction_target_required'),
        ),
    ]
