# Generated by Django 4.2 on 2026-04-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0008_compatibilitytransaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='public_match',
            field=models.BooleanField(default=True),
        ),
    ]
