# Generated by Django 4.2 on 2026-04-19 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0011_userprofile_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('rank', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('matched_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matchmaking.userprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='matchmaking.userprofile')),
            ],
            options={
                'ordering': ['rank', '-score'],
            },
        ),
        migrations.AddIndex(
            model_name='usermatch',
            index=models.Index(fields=['user', '-score'], name='matchmaking_user_id_1f4a91_idx'),
        ),
        migrations.AddIndex(
            model_name='usermatch',
            index=models.Index(fields=['user', 'rank'], name='matchmaking_user_id_d02034_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='usermatch',
            unique_together={('user', 'matched_user')},
        ),
    ]
