# Generated by Django 4.2 on 2026-04-20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0012_usermatch_usermatch_matchmaking_user_id_1f4a91_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('cancelled', 'Cancelled'), ('disconnected', 'Disconnected')], default='pending', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile_high', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='matchmaking.userprofile')),
                ('profile_low', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='matchmaking.userprofile')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_connections', to='matchmaking.userprofile')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_connections', to='matchmaking.userprofile')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddIndex(
            model_name='userconnection',
            index=models.Index(fields=['requester', 'status', '-updated_at'], name='matchmaking_request_78b61c_idx'),
        ),
        migrations.AddIndex(
            model_name='userconnection',
            index=models.Index(fields=['receiver', 'status', '-updated_at'], name='matchmaking_receive_1e08ef_idx'),
        ),
        migrations.AddIndex(
            model_name='userconnection',
            index=models.Index(fields=['profile_low', 'profile_high'], name='matchmaking_profile_c4cc47_idx'),
        ),
        migrations.AddIndex(
            model_name='userconnection',
            index=models.Index(fields=['status', '-updated_at'], name='matchmaking_status_47054c_idx'),
        ),
        migrations.AddConstraint(
            model_name='userconnection',
            constraint=models.UniqueConstraint(fields=('profile_low', 'profile_high'), name='unique_user_connection_pair'),
        ),
        migrations.AddConstraint(
            model_name='userconnection',
            constraint=models.CheckConstraint(check=models.Q(('requester', models.F('receiver')), _negated=True), name='user_connection_requester_not_receiver'),
        ),
    ]
