# Generated by Django 4.2 on 2026-04-21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0013_userconnection'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('user_a_unread_count', models.PositiveIntegerField(default=0)),
                ('user_b_unread_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chat_conversation', to='matchmaking.userconnection')),
                ('user_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_conversations_as_user_a', to='matchmaking.userprofile')),
                ('user_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_conversations_as_user_b', to='matchmaking.userprofile')),
            ],
            options={
                'ordering': ['-last_message_at', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('client_message_id', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='matchmaking.chatconversation')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_chat_messages', to='matchmaking.userprofile')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_chat_messages', to='matchmaking.userprofile')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='chatconversation',
            name='last_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='matchmaking.chatmessage'),
        ),
        migrations.AddField(
            model_name='chatconversation',
            name='user_a_last_read_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='matchmaking.chatmessage'),
        ),
        migrations.AddField(
            model_name='chatconversation',
            name='user_b_last_read_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='matchmaking.chatmessage'),
        ),
        migrations.AddIndex(
            model_name='chatconversation',
            index=models.Index(fields=['user_a', '-last_message_at'], name='matchmaking_user_a__b2bdec_idx'),
        ),
        migrations.AddIndex(
            model_name='chatconversation',
            index=models.Index(fields=['user_b', '-last_message_at'], name='matchmaking_user_b__a9ecbd_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['conversation', '-created_at', '-id'], name='matchmaking_convers_ee2874_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['sender', 'client_message_id'], name='matchmaking_sender__c3f202_idx'),
        ),
        migrations.AddConstraint(
            model_name='chatconversation',
            constraint=models.CheckConstraint(check=models.Q(('user_a', models.F('user_b')), _negated=True), name='chat_conversation_distinct_users'),
        ),
        migrations.AddConstraint(
            model_name='chatmessage',
            constraint=models.UniqueConstraint(fields=('sender', 'client_message_id'), name='unique_chat_client_message'),
        ),
        migrations.AddConstraint(
            model_name='chatmessage',
            constraint=models.CheckConstraint(check=models.Q(('sender', models.F('receiver')), _negated=True), name='chat_message_sender_not_receiver'),
        ),
    ]
