# Generated by Django 4.2 on 2026-04-24 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0014_chatconversation_chatmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compatibilityscore',
            name='mars_compatibility',
        ),
        migrations.RemoveField(
            model_name='compatibilityscore',
            name='moon_compatibility',
        ),
        migrations.RemoveField(
            model_name='compatibilityscore',
            name='sun_compatibility',
        ),
        migrations.RemoveField(
            model_name='compatibilityscore',
            name='venus_compatibility',
        ),
        migrations.AddField(
            model_name='compatibilityscore',
            name='chemistry',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compatibilityscore',
            name='compatibility',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compatibilityscore',
            name='destiny',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compatibilityscore',
            name='durability',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compatibilityscore',
            name='friendship',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compatibilityscore',
            name='sizzle',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compatibilityscore',
            name='waity',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
